name: My First Workflow
on: 
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  first_job:
    name: My first Job
    runs-on: ubuntu-latest
    steps:
        - run: | 
            echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}." 
            echo "My secret is ${{ secrets.MY_SECRET}}."
        - name: Checkout 
          uses: actions/checkout@v5.0.0
        - run: tree
        
        
