name: My First Workflow
on: 
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  first_job:
    name: My first Job
    runs-on: ubuntu-latest
    steps:
        - run: | 
            echo "Hello World from " 
            echo "Current branch is main branch."
        - name: Checkout 
          uses: actions/checkout@v5.0.0
        - run: tree
        
        
